feat: Husky mode
microservices-course-itmo/deployer pull request #11
Opened 2020-10-05 12:57 UTC by DanilaPichugin

Set Husky settings

2020-10-05 13:09 UTC, MaximLukianchuk requested changes

2020-10-05 13:09 UTC, MaximLukianchuk commented on .prettierrc
> -  "tabWidth": 2,
а почему здесь убрал?

2020-10-05 13:09 UTC, MaximLukianchuk commented on package.json
> -  "name": "deployer",
1) неудобно смотреть изменения, когда в одном коммите и отступы везде поменял и дргие изменения делал (не видно что изменилось)
2) а зачем ты изменяешь ширину отступа?

2020-10-05 13:17 UTC, DanilaPichugin commented on .prettierrc
> -  "tabWidth": 2,
Сейчас исправлю, случайно заменил на строчку "endOfLine:auto" вместо того, чтобы ее добавить.

2020-10-05 13:27 UTC, DanilaPichugin commented on package.json
> -  "name": "deployer",
Видимо, ты пишешь про предыдущую проблему, которую я исправил.

2020-10-05 13:29 UTC, MaximLukianchuk commented on package.json
> -  "name": "deployer",
правило отступов то ты вернул, а сами отступы нет, запусти линтер

2020-10-11 15:20 UTC, MaximLukianchuk commented
!lgtm

2020-10-11 15:20 UTC, MaximLukianchuk approved these changes
LGTM

2020-10-11 15:20 UTC, merged