fix: Alias field is made unrequired for accessing the Deploy Button
microservices-course-itmo/deployer pull request #33
Opened 2020-11-10 09:32 UTC by DanilaPichugin

Alias field is made optional for accessing the Deploy Button

2020-11-11 14:31 UTC, MaximLukianchuk requested changes

2020-11-11 14:31 UTC, MaximLukianchuk commented on src/pages/ApplicationPage/tabs/ApplicationPageTabDeploy/ApplicationPageTabDeploy.tsx
>  }: IApplicationPageTabDeployProps) => {
получилась странная логика
при клике на деплой - версия стирается, а алиасик нет..
кажется нужно все наоборот сделать

и получается, что кнопку вообще блокировать не надо

2020-11-11 18:21 UTC, DanilaPichugin commented on src/pages/ApplicationPage/tabs/ApplicationPageTabDeploy/ApplicationPageTabDeploy.tsx
>  }: IApplicationPageTabDeployProps) => {
Исправил в следующем коммите)

2020-11-13 15:14 UTC, MaximLukianchuk approved these changes
LGTM!

2020-11-18 14:05 UTC, merged