DEV_MainPage
microservices-course-itmo/deployer pull request #5
Opened 2020-09-28 17:35 UTC by ovchingus

2020-10-09 21:02 UTC, alexstrive commented
Что по прогрессу? @ovchingus

2020-10-11 15:39 UTC, MaximLukianchuk requested changes

2020-10-11 15:39 UTC, MaximLukianchuk commented on .eslintrc.json
> +    "react/prop-types": 0
почему убрал правило 'react/prop-types' ?
мы не юзаем проп тайпсы

2020-10-11 15:39 UTC, MaximLukianchuk commented on build-tools/webpack.config.js
> -        filename: 'assets/js/[name].[contenthash].js',
это все пофикшено
помержись, пж, от свежего DEV

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/Menu.tsx
> +// import PropTypes from 'prop-types'
удоли

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/Menu.tsx
> +    // eslint-disable-next-line react/jsx-props-no-spreading
eslint-disable просто так не используем, добавь, пж, правило в eslint конфиг

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/Menu.tsx
> +// Menu.propTypes = {
проптайсы удоляй

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/Menu.tsx
> +
```
interface IMenuProps {
    open: () => void;
    children: React.ReactNode;
    ...
    ...
}
```

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/Menu.tsx
> +const Menu = ({ open, anchorEl, onClose, children, ...otherProps }) => (
```const Menu = ({ open, anchorEl, onClose, children, ...otherProps }: IMenuProps) => (```

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/Menu.tsx
> +Menu.defaultProps = {
удоляй
используй дефолтные значения при деструктуризации пропсов

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/MenuItem/MenuItem.tsx
> +// import PropTypes from 'prop-types'
удоляй

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/MenuItem/MenuItem.tsx
> +// MenuItem.propTypes = {
ремув

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/MenuItem/MenuItem.tsx
> +MenuItem.defaultProps = {
ремув

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/MenuItem/MenuItem.tsx
> +const MenuItem = React.forwardRef(
```
interface IMenuItem {
    button: ...;
    ...
}
```

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Menu/MenuItem/MenuItem.tsx
> +        // eslint-disable-next-line react/jsx-props-no-spreading
ремув

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Table/Table.tsx
> +const Table = (
```
interface ITableProps {
    className: string;
    gridTemplate: ...;
    ...
}
```

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Table/Table.tsx
> +    // eslint-disable-next-line no-nested-ternary
ремув

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Table/Table.tsx
> +      // eslint-disable-next-line react/jsx-props-no-spreading
ремув

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Table/Table.tsx
> +                // eslint-disable-next-line
удоли

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Table/Table.tsx
> +Table.defaultProps = {
ремув

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Table/Table.tsx
> +      {Boolean(isTableEmpty && !isLoading && emptyText) && (
не читаются такие конструкции
можешь наверх вынести флаги в переменные?

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Table/TableEmpty/TableEmpty.tsx
> +const TableEmpty = ({
```
interface ITableEmpty {
    emptyText: string;
    ...
}
```

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Table/TableEmpty/TableEmpty.tsx
> +      className={cx(
все такое говно в переменные

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/components/Table/TableHead/TableHead.tsx
> +const TableHead = ({
```
interface ITableHead {
    className: string;
    ...
}
```

2020-10-11 15:39 UTC, MaximLukianchuk commented on src/definitions.ts
> +  MAIN: {
гуд идея
а что предполагаешь в будущем еще кроме path хранить в объекте?

2020-12-18 09:29 UTC, closed without merging