Dev profile page styles
microservices-course-itmo/deployer pull request #72
Opened 2021-03-24 22:37 UTC by dropex7

2021-03-24 22:45 UTC, MaximLukianchuk requested changes

2021-03-24 22:45 UTC, MaximLukianchuk commented on .env.dev
> +API=http://77.234.215.138:18080/deployment-service
думаю лучше оставить ссылку на локальный апи

2021-03-24 22:45 UTC, MaximLukianchuk commented on public/index.html
>  <!DOCTYPE html>
странно, что есть изменения в этом файле

2021-03-24 22:45 UTC, MaximLukianchuk commented on src/pages/Profile/ProfilePage.tsx
> +          fetch(`http://77.234.215.138:18080/user-service/users/${data.id}/full`)
давай не будем уходить в адд коллбеком и сделаем так:
```
...
.then((res) => res.json())
.then((data) => {
        return fetch(`http://77.234.215.138:18080/user-service/users/${data.id}/full`)
}
.then((result) => result.json())
.then((info) => {
        setUserData(info)
        console.log(info)
})
```

2021-03-24 22:45 UTC, MaximLukianchuk commented on src/pages/Profile/ProfilePage.tsx
> +          fetch(`http://77.234.215.138:18080/user-service/users/${data.id}/full`)
ну и консоль лог давай уберем уж)

2021-03-24 22:45 UTC, MaximLukianchuk commented on src/pages/Profile/ProfilePage.tsx
> +                  <span>Phone Number: </span>{' '}
поч пробел а не пустая строка?)
а давай сделаем initialState и пусть там сразу будут пустые строки?
```
...
const [userData, setUserData] = useState({..., phoneNumber: '',birthdate: '', ...})
...
```

2021-03-24 22:48 UTC, DanilaPichugin reviewed
Good!

2021-03-24 22:49 UTC, DanilaPichugin approved these changes

2021-03-25 13:38 UTC, ovchingus requested changes
В целом неплохо но есть ньюансы.

2021-03-25 13:38 UTC, ovchingus commented on src/pages/Profile/ProfilePage.tsx
> +          fetch(`http://77.234.215.138:18080/user-service/users/${data.id}/full`)
Лучше вынести в `.env` файл

2021-03-25 13:38 UTC, ovchingus commented on src/pages/Profile/ProfilePage.tsx
> +    padding: '0px 1rem',
Можно просто `0 1rem`

2021-03-25 13:38 UTC, ovchingus commented on src/pages/Profile/ProfilePage.tsx
> +    minWidth: '25rem',
Почему `minWidth` измеряется в rem ?

2021-03-25 14:43 UTC, MaximLukianchuk approved these changes
LGTM

2021-03-25 14:43 UTC, merged