Codestyle kletsyn
microservices-course-itmo/deployer pull request #74
Opened 2021-03-25 14:48 UTC by constantkek

Refactored auth components, settings component and main page component

2021-03-25 16:46 UTC, MaximLukianchuk requested changes

2021-03-25 16:46 UTC, MaximLukianchuk commented on src/pages/LoginPage/LoginPage.tsx
> +          fetch(`${process.env.API}/user-service/login`, data as RequestInit)
process.env.API это наш
а тут ходим к юзер сервису
нужно в .env.dev добавить API_USER_SERVICE

2021-03-30 15:05 UTC, constantkek commented
@MaximLukianchuk исправил

2021-03-31 21:58 UTC, MaximLukianchuk requested changes

2021-03-31 21:58 UTC, MaximLukianchuk commented on src/pages/SettingsPage/Settings.tsx
> +  const accessToken = window.localStorage.getItem('accessToken') || '0'
мммм, а зачем  || '0'?
го как было

2021-03-31 21:58 UTC, MaximLukianchuk commented on src/pages/NewAppPage/NewAppPage.tsx
> +    ...values,
давай это вначала, чтобы поля не переопределялись

2021-04-01 11:49 UTC, MaximLukianchuk approved these changes
LGTM

2021-04-01 11:49 UTC, merged