Modal deploy
microservices-course-itmo/deployer pull request #77
Opened 2021-03-30 16:46 UTC by constantkek

Wrapped deploy input fields into modal

2021-03-30 17:43 UTC, MaximLukianchuk requested changes

2021-03-30 17:43 UTC, MaximLukianchuk commented on src/pages/ApplicationPage/Deploy.tsx
> +            <Button variant='contained' disabled={!version} onClick={setModalState(true)}>
в onClick нужно передавать коллбек, который вызовется при клике
а тут ты получается прямо в методе рендера - вызываешь setModalState, который в свою очередь повтороно вызовет рендер

2021-03-31 21:03 UTC, MaximLukianchuk approved these changes
LGTM!

2021-03-31 21:05 UTC, DanilaPichugin approved these changes
Good idea to wrap into modal.

2021-03-31 21:11 UTC, MaximLukianchuk approved these changes
LGTM

2021-03-31 21:12 UTC, merged